AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CustomResource:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: !GetAtt CustomLambdaFunction.Arn
  CustomLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              print("Custom Resource Logic")
      Runtime: python3.8